[tool.poetry]
name = "porec"
version = "0.1.0"
description = ""
authors = ["takeru1205 <takeru0639418@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
